### ISSUE TITLE
rails pg database.yml 配置不正确

### ISSUE THREAD

**Issue by defrur** [defrur/tech-notes#1]
### 关键配置
```
development:
  adapter: postgresql
  encoding: unicode
  database: rails_assets_development
  pool: 30
  username: homestead
  password: "secret"

```
### 设置数据库
```
rake db:setup
```

### 出错
```
Couldn't create database for {"adapter"=>"postgresql", "encoding"=>"unicode", "database"=>"rails_assets_development", "pool"=>30, "username"=>"homestead", "password"=>"secret"}
FATAL:  Peer authentication failed for user "homestead"
```

**Comment by defrur** [comment]
正确的配置举例如下。其中 host 是不能少的。

```
development:
  adapter: postgresql
  host: localhost
  encoding: unicode
  database: rails_assets_development
  pool: 30
  username: homestead
  password: "secret"
```
